name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/puer
  - packages/puer_test
  - packages/puer_flutter
  - packages/puer_time_travel
  - packages/puer_time_travel_devtools_extension

dev_dependencies:
  melos: ^7.4.0
  flutter_lints: ^6.0.0

melos:
  scripts:
    test:
      run: dart pub run melos exec --dir-exists=test -- "flutter test"
      description: Run `flutter test` in all packages