name: puer_flutter
description: A bunch of widgets that helps you to easily works with puer with Flutter.
version: 1.0.0-alpha.1

repository: https://github.com/Vorkytaka/puer
issue_tracker: https://github.com/Vorkytaka/puer/issues
homepage: https://github.com/Vorkytaka/puer
topics:
  - state-management
  - architecture
  - unidirectional-data-flow
  - mvi

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.0
  puer: ^1.0.0-alpha.1
  provider: ^6.0.0
  rxdart: '>=0.27.0 <1.0.0'

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
