name: puer_time_travel
description: Drop-in time-travel debugging for puer. Record every message and state snapshot, then step backward and forward through history using Flutter DevTools extension.
version: 1.0.0-alpha.2

repository: https://github.com/Vorkytaka/puer/tree/master/packages/puer_test
issue_tracker: https://github.com/Vorkytaka/puer/issues
homepage: https://github.com/Vorkytaka/puer
topics:
  - state-management
  - architecture
  - unidirectional-data-flow
  - mvi
  - time-travel

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  meta: ^1.0.0
  puer: ^1.0.0-alpha.1
  test: ^1.16.0

dev_dependencies:
  puer_lints: ^1.0.0
